typography_spectrum: 0.5947329995688051
color:
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  brandStrength: 0.06023947894573212
  lightness: 0.046355585334822536
  saturation: 0.5437687952071428
  rhythmicContrast: 0.0453396060038358
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8687803994398564
analytics:
  google: null
  facebook: null
  twitter: null
name: Leigh MacArthur Photography
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Me
    url: 'http://www.leighmacarthur.com/about-me'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Leigh MacArthur '
description: Photography
purpose: []
