name: Leigh MacArthur Photography
favicon: null
layout_spectrum: 0.19615
typography_spectrum: 0.5220191981643438
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.08175600203685462
  lightness: 0.9398522565606982
  saturation: 0.515344861196354
  rhythmicContrast: 0.7501173063647002
purpose: []
