typography_spectrum: 0.6298734915908426
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.5340507689397782
  lightness: 0.9570050400216132
  saturation: 0.8701288639567792
  rhythmicContrast: 0.476179248187691
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5679268215317279
analytics:
  google: null
  facebook: null
  twitter: null
name: Leigh MacArthur Photography
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Starting Down the Path of Photography
    id: d3f5c7fe-a595-4444-bfaa-442ff3a630d9
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Leigh MacArthur '
purpose: []
